//All Products List Constants
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

//Single Product Details Constants
export const ONE_PRODUCT_REQUEST = 'ONE_PRODUCT_REQUEST'
export const ONE_PRODUCT_SUCCESS = 'ONE_PRODUCT_SUCCESS'
export const ONE_PRODUCT_FAILED = 'ONE_PRODUCT_FAILED'

//Product Add Constants
export const PRODUCT_ADD_BA_REQUEST = 'PRODUCT_ADD_BA_REQUEST'
export const PRODUCT_ADD_BA_SUCCESS = 'PRODUCT_ADD_BA_SUCCESS'
export const PRODUCT_ADD_BA_FAILED = 'PRODUCT_ADD_BA_FAILED'
export const PRODUCT_ADD_BA_RESET = ' PRODUCT_ADD_BA_RESET'

//Product Details Edit Constants
export const PRODUCT_EDIT_BA_REQUEST = 'PRODUCT_EDIT_BA_REQUEST'
export const PRODUCT_EDIT_BA_SUCCESS = 'PRODUCT_EDIT_BA_SUCCESS'
export const PRODUCT_EDIT_BA_FAILED = 'PRODUCT_EDIT_BA_FAILED'
export const PRODUCT_EDIT_BA_RESET = 'PRODUCT_EDIT_BA_RESET'

//Product Delete Constants
export const PRODUCT_DELETE_BA_REQUEST = 'PRODUCT_DELETE_BA_REQUEST'
export const PRODUCT_DELETE_BA_SUCCESS = 'PRODUCT_DELETE_BA_SUCCESS'
export const PRODUCT_DELETE_BA_FAILED = 'PRODUCT_DELETE_BA_FAILED'

//Cart Constants
export const CART_ADD_ITEM = 'CARD_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CARD_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

//User Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

//User Register Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

//User Details Constants
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

//User Details Update Constants
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILED = 'USER_UPDATE_PROFILE_FAILED'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

//Get all Users for Admin Constants
export const USER_LIST_BA_REQUEST = 'USER_LIST_BA_REQUEST'
export const USER_LIST_BA_SUCCESS = 'USER_LIST_BA_SUCCESS'
export const USER_LIST_BA_FAILED = 'USER_LIST_BA_FAILED'
export const USER_LIST_BA_RESET = 'USER_LIST_BA_RESET'

//Delete User by Admin Constants
export const USER_DELETE_BA_REQUEST = 'USER_DELETE_BA_REQUEST'
export const USER_DELETE_BA_SUCCESS = 'USER_DELETE_BA_SUCCESS'
export const USER_DELETE_BA_FAILED = 'USER_DELETE_BA_FAILED'

//Update User by Admin Constants
export const USER_UPDATE_BA_REQUEST = 'USER_UPDATE_BA_REQUEST'
export const USER_UPDATE_BA_SUCCESS = 'USER_UPDATE_BA_SUCCESS'
export const USER_UPDATE_BA_FAILED = 'USER_UPDATE_BA_FAILED'
export const USER_UPDATE_BA_RESET = 'USER_UPDATE_BA_RESET'

//Order Create Constants
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED'

//Orders Details Constants
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED'

//Order Pay Constants
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILED = 'ORDER_PAY_FAILED'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

//Logged In User Orders Constants
export const MY_ORDERS_LIST_REQUEST = 'MY_ORDERS_LIST_REQUEST'
export const MY_ORDERS_LIST_SUCCESS = 'MY_ORDERS_LIST_SUCCESS'
export const MY_ORDERS_LIST_FAILED = 'MY_ORDERS_LIST_FAILED'
export const MY_ORDERS_LIST_RESET = 'MY_ORDERS_LIST_RESET'
